version: '3.8'
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    ports:
      - "5000:80"
    depends_on:
      - postgres
    environment:
      - ConnectionStrings__DefaultConnection=Host=localhost;Port=5432;Database=postgres;User Id=postgres;Password=password;

  web:
    build:
      context: .
      dockerfile: Dockerfile.web
    ports:
      - "5001:80" # Map your Web app port to the desired host port
    depends_on:
      - api

  postgres:
    image: postgres:latest
    container_name: postgres
    ports:
      - "5432:5432" # Map PostgreSQL port to the desired host port
    environment:
      POSTGRES_USER: YourUsername
      POSTGRES_PASSWORD: YourPassword
      POSTGRES_DB: YourDatabaseName