version: '3.8'

services:
  api:
    image: ilya3004/todo:api
    build:
      context: .
      dockerfile: src/Api/Dockerfile
    ports:
      - "8181:80"
    environment:
      - ConnectionStrings__DefaultConnection=Host=postgres;Port=5432;Database=postgres;User Id=postgres;Password=password;
      - LogFilePath=logs/log.txt;
    depends_on:
      - postgres  
    volumes:
      - logs:/app/logs/
    networks:
      - dev

  postgres:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    networks:
      - dev
    volumes:
      - postgres_data:/var/lib/postgresql/data

networks:
  dev:
    driver: bridge

volumes: 
  logs:
  postgres_data: