version: '3.8'

networks:
  dev:
    driver: bridge

services:
  api:
    build:
      context: .
      dockerfile: src/Api/Dockerfile
    ports:
      - "5074:80"
    environment:
      - ConnectionStrings__DefaultConnection=Host=postgres;Port=5432;Database=postgres;User Id=postgres;Password=password;
    depends_on:
      - postgres
    networks:
      - dev

  postgres:
    image: postgres
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"  
    networks:
      - dev

